name: Telegram Notification

on:
  schedule:
    - cron: "0 */8 * * *"
  push:
    branches:
      - master
      - gh-pages
  pull_request:
    branches:
      - master
      - gh-pages
  repository_dispatch:
    types: [notify]
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
